name: ffmpeg build test

on:
  workflow_dispatch:

jobs:
  ffmpeg-upload-all:
    name: Upload ffmpeg
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup vcpkg (if needed)
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg.exe install ffmpeg[core,avcodec,avformat,avfilter,swscale,swresample,amf,x264,x265,nvcodec,openh264,aom,vpx]:x64-windows-static --recurse

    - name: Zip entire workspace
      run: |
        Compress-Archive -Path * -DestinationPath full_output.zip

    - name: Upload full ffmpeg zip
      uses: actions/upload-artifact@v4
      with:
        name: full-ffmpeg
        path: full_ffmpeg.zip
