name: ffmpeg build test

on:
  workflow_dispatch:

jobs:
  test-workflow-structure:
    name: Test GitHub Actions Workflow (No Build)
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Simulate steps (no vcpkg install)
      run: |
        echo Simulating vcpkg install step...
        mkdir dlls
        echo dummy > dlls\dummy.dll
        echo Collecting dummy dlls...
        dir dlls

    - name: Zip dummy DLLs
      run: Compress-Archive -Path dlls\* -DestinationPath windows_dlls.zip

    - name: Upload dummy zip
      uses: actions/upload-artifact@v4
      with:
        name: test-windows-dlls
        path: windows_dlls.zip
